Documentation/deployment-and-configuration.md, agent/agent.go, agent/reconcile.go, agent/state.go, agent/unit_state.go, api/mux.go, engine/engine.go, engine/reconciler.go, etcd/client.go, fleetctl/fleetctl.go, fleetctl/stop.go, fleetctl/unload.go, fleetd/fleet.go, heart/monitor.go, log/log.go, machine/coreos.go, machine/machine.go, pkg/filepath.go, pkg/http.go, pkg/reconcile.go, registry/event.go, ssh/known_hosts.go
We don't utilize the multi-leveled logs, so let's just drop that overly-complex code. Use `log.Debug[f]` instead.
=> log: replace V-levels with Debug method

Documentation/using-the-client.md, fleetctl/fleetctl.go, fleetctl/journal.go, fleetctl/ssh.go
I needed this functionality and noticed everything seemed pretty close. My last commit here makes all commands work correctly for me.
There is one caveat that I documented in using-the-client. The `journal` command executes `journalctl` which needs permission to view the journald files. I added a `--sudo` flag to the journal command as a solution but I can't say I'm extremely happy with it but it should work by default since the sudo group is passwordless.
Linking:
Updates #1076 to fix [comment][1] from #904 and should finally close #536
[1]: https://github.com/coreos/fleet/pull/904#issuecomment-55839865
=> Finish SSH Username Support

fleetctl/status.go
Fixes #1021 on github.
If the exit code of systemd is not 0, then return with that exit code.
Previous behavior was to break and return 0.
The github.com/coreos/fleet/ssh test fails on master (at least on arch linux), and my PR does nothing to change that.
I don't see any tests for status. Will any be necessary?
=> status: fix return code for stopped units

functional/platform/nspawn.go
Intermittently systemctl is reporting the following error during
poweroff:
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
This seems harmless but don't have a solution yet. For now at least
report the error to make the issue more obvious.
=> nspawn: report error message from poweroff

Documentation/states.md
Hi,
I noticed that https://github.com/coreos/fleet/blob/master/Documentation/states.md is out of date. It mentions the `fleetctl show-schedule` command, which doesn't seem to exist anymore:
```
$ fleetctl version
fleetctl version 0.8.3
$ fleetctl show-schedule
fleetctl: unknown subcommand: "show-schedule"
``` 
I'm not familiar enough with fleet yet to say whether any other information about valid states and transitions between them is out-of-date, but maybe it should also be reviewed.
Cheers,
Henrik
=> Unit states documentation is out of date

agent/reconcile.go, agent/reconcile_test.go, agent/task.go, agent/task_test.go
On master, a given fleet agent reconciles its current state against the desired state by generating a set of taskChain objects. A taskChain is a series of tasks that should be executed against a given unit. For example, a new unit is started on an agent with a taskChain containing a LoadUnit and a StartUnit task. A unit file is replaced with a chain of UnloadUnit, LoadUnit, StartUnit. The flaw here, however, is that there isn't any ordering between the execution of the taskChains themselves. So if you have unit foo.service that BindsTo bar.service, fleet will race to start them both, and sometimes foo.service will fail with "No such file or directory" since bar.service may not have actually been written to disk yet.
The alternative proposed here is to throw the taskChain concept out the …
=> Ordered task execution

fleetctl/status.go
fixes #1154 allowing support for `systemd-escape`ed filenames in status command while tunneling.
=> Use escape format ("%q") in fmt.Sprintf() in status command

agent/agent.go, agent/reconcile.go, agent/reconcile_test.go, agent/task.go, systemd/manager.go, unit/fake.go, unit/manager.go
This eliminates the raciness of calling DaemonReload during reconciliation by making it an explicit task that gets executed after all LoadUnit & UnloadUnit tasks complete.
Fix #1158.
=> Call DaemonReload after all Load/Unload operations complete

version/version.go
Bump to latest released version, otherwise building fleet from master and running against a running cluster yields:
WARNING: fleetctl (0.9.0+git) is older than the latest registered version of fleet found in the cluster (0.9.1).
=> version: bump to v0.9.1+git

fleetctl/fleetctl.go, fleetctl/journal.go, fleetctl/ssh.go, fleetctl/status.go
This allows end users to specify a custom SSH port with fleetctl when connecting to machines.
This is code that was split out from PR #961 by @ryandub
=> fleetctl: Allow a custom SSH port

Documentation/deployment-and-configuration.md, Documentation/using-the-client.md, etcd/client.go, etcd/client_test.go, fleet.conf.sample, functional/platform/nspawn.go
Fixes https://github.com/coreos/fleet/issues/1171.
=> fleetd: try ports 2379 and 4001 by default for etcd

fleetctl/ssh.go
#1148 added in the `ssh-port` flag to fleetctl (thanks @hhoover !!). However, there was a slight omission in `ssh.go` to add the port context to `runCommand`. This adds that info so that `--ssh-port` works as expected.
=> fleetctl: Add ssh-port info to ssh runCommand func

functional/platform/nspawn.go
A follow up to 529209534, tests are constantly failing with a dbus error
which is probably a bug in systemd or systemctl. Not worth spending lots
of time on right now so just ignore it. If the container really fails to
shutdown the wait will eventually time out instead.
=> functional: ignore errors from poweroff

functional/unit_action_test.go
TestUnitSSHAction is failing due to no journal output. Using recent CoreOS builds, one has to `sudo journalctl`. Adding the `--sudo` flag to `fleectl journal` addresses the problem.
=> functional: use --sudo with fleetctl journal commands

fleetctl/fleetctl.go
=> Switch default fleetctl driver to API

functional/platform/nspawn.go
The --experimental-api flag is deprecated and has no effect
on the fleetctl commands run by the functional tests.
=> functional/platform: remove --experimental-api

api/server.go
This does not address all aspects of #1203, but it does take an important step towards directing the user to etcd. Here's what a user will see now:
```
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
```
=> api: be more specific when unavailable

fleetctl/fleetctl.go
There is one remaining wart of the switch from --driver=etcd to --driver=API. If someone had been using fleetctl with a custom endpoint like so:
```
fleetctl --endpoint http://example.com:4001 list-machines
```
They now all of a sudden get directed to the fleet API rather than etcd. Given that we can tell (based on the port) that the user wants to use etcd, the default of --driver in this case should remain "etcd".
=> fleetctl: set --driver=etcd if --endpoint is etcd-like

fleetd/fleet.go
Now support "fleetd version" and "fleetd --version"
Fixes #1210
=> fleetd: support the version command

fleetd/fleet.go
Commit 32a51814 broke fleetd, making "fleetd version" the *only* thing it
could do and causing a index error panic otherwise. Now in addition to
properly checking the number of unparsed args exit with a usage error if
given any other unknown arguments.
Simply exiting if there are any unparsed args would have been sufficient
to fix #1210 but on the other hand allowing "fleetd version" doesn't
hurt so might as well keep it.
Fixes #1214 and #1210
=> fleetd: fix support for "fleetd version"

fleetctl/status.go
This reverts commit 9b8ee4b5b67d4086de0a1cd72237f9a1cae5bf8e.
This was breaking all remote fleetctl status commands as they were
passing escaped quotes to systemctl.
=> Revert "fleetctl: use correct escape format in status command"

fleetctl/journal.go, fleetctl/ssh.go, fleetctl/status.go
Remote commands need to be escaped because they are being interpretted
by a shell. Local commands, however, cannot be because they are being
exec'd. Additionally, splitting an opaque command by space is very error
prone (e.g. `ls "dumb filename"`).
=> fleetctl: properly run local and remote commands

.travis.yml, README.md, build-aci, build-docker, test-docker
using tools from code.google.com with go1.3 is now breaking.
https://travis-ci.org/coreos/fleet/jobs/68876752
=> move to go 1.4

fleetctl/fleetctl.go
When start unit, if [X-Fleet] give peer by "MachineOf=", the
fleetctl cannot know the exact reason. Only fleetd check the peer.
But still we can give a DEBUG print to inform launch is happing.
It's not the problem that the peer is not existing. After the
peer is running, the fleetctl will go on to the end. So just
add a debug print if --debug=true is given to fleetctl.
Fixes #1146
=> fleetctl: Give DEBUG print if need wait for launch when start unit

scripts/fleetctl-remove-ssh-user.sh, scripts/fleetctl-replace-ssh-keys.sh
fleetctl-inject-ssh.sh is a good tool for granting access to the core
user, but it is unable to replace SSH keys or revoke access; this change
adds two scripts to do this.
Usage:
`cat ~/.ssh/*pub | ./fleetctl-replace-ssh-key.sh USER`
`./fleetctl-remove-ssh-user USER`
The above are orthogonal to:
`cat ~/.ssh/*pub | ./fleetctl-inject-ssh.sh USER`
=> scripts: add SSH key replacement & removal

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/etcd/client/auth_role.go, Godeps/_workspace/src/github.com/coreos/etcd/client/auth_user.go, Godeps/_workspace/src/github.com/coreos/etcd/client/client.go, Godeps/_workspace/src/github.com/coreos/etcd/client/client_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/keys.go, Godeps/_workspace/src/github.com/coreos/etcd/client/keys_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/members.go, Godeps/_workspace/src/github.com/coreos/etcd/client/members_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/urlsmap.go, registry/job.go, registry/machine.go, registry/unit.go
this fixes a race encountered when fleetd does a PUT followed by GET but does not use `quorum=true` for the get, resulting in a 404 from the local etcd.
/cc @bcwaldon @jonboulle @marineam
=> consistent reads

fleetctl/status.go
Use the Unit API instead of Units API to speed up lookups on
environments with a large number of distinct services.
Fixes #1340
=> fleetctl: optimize status command

Documentation/api-v1.md
The documentation can be confusing when not knowing `/fleet/v1` has to be added in front of all requests.
=> Add '/fleet/v1' to all calls

api/machines.go, api/machines_test.go, api/mux.go, api/mux_test.go, api/pagination.go, api/pagination_test.go, api/state.go, api/state_test.go, api/units.go, api/units_test.go, config/config.go, fleetd/fleetd.go, server/server.go
Make tokenLimit in api public and add a flag to fleet.conf (token_limit)
to override the built-in token limit of 100.
Note: this PR is rather *hackish*, it would be nice to know if something like will be considered for merging (if cleaned up, etc .etc.). IOW: comments welcome!
=> Add flag to override tokenLimit

Documentation/architecture.md, Documentation/fleet-scaling.md, config/config.go, fleetd/fleetd.go, server/server.go
If set this fleetd will never assume mastership in a fleet cluster.
This will cut down on the interactions with Etcd.
Note: this PR is rather *hackish*, it would be nice to know if something like will be considered for merging (if cleaned up, etc .etc.). IOW: comments welcome!
Fix #1166
=> Implement follow_only flag

fleetd/fleetd.go
We were calling userset.Usage but it was never actually defined. Unlike
in the top-level of the flag package (i.e. `flag.Usage`), this method
does not have a default value on `FlagSet`s.
The only reason this never showed up way earlier in the `ErrHelp` path
(and was only revealed via 8ebb81bcd1668be4a874db98cbf2e67ae305d7f6)
is that branch was never actually encountered.
Fixes #1360
=> fleetd: fix argument handling

registry/job.go, registry/unit.go, unit/unit.go, unit/unit_test.go
=> *: consolidate excessive Hash/Unit requests

build
When building fleet with go1.5 we got the following warning:
Building fleetd...
link: warning: option -X github.com/coreos/fleet/version.Version v0.10.1-117-g7b2a547 may not work in future releases; use -X github.com/coreos/fleet/version.Version=v0.10.1-117-g7b2a547
Building fleetctl...
link: warning: option -X github.com/coreos/fleet/version.Version v0.10.1-117-g7b2a547 may not work in future releases; use -X github.com/coreos/fleet/version.Version=v0.10.1-117-g7b2a547
Newer go versions will only support '-X name=value' format, so make our
build system smarter. It will make sure to use the right format for
future builds.
Reference:
https://github.com/golang/go/issues/13498
Patch written by: Eugene Yakubovich
https://github.com/coreos/flannel/blob/master/build
=> fleet:build: remove build warnings on go1.5

build-docker
otherwise `./build-docker` will produce binaries owned by root
=> Use current user UID inside docker

Documentation/states.md
=> docs: renamed "etcd storage" into "etcd registry"

Documentation/unit-files-and-scheduling.md
/cc @joshix @robszumski @jonboulle 
resolves https://github.com/coreos/fleet/issues/1411
=> docs: Added detailed explanation on fleet's Metadata logic

Documentation/fleet-scaling.md, config/config.go, fleetd/fleetd.go, server/server.go
Setting this flag to true makes fleet not set any watches in etcd.
=> Add --disable_watches flag

fleetd/fleetd.go
It's a common mistake for users to accidentally invoke fleet (which is,
unfortunately, a symlink to fleetd on CoreOS) instead of fleetctl, which
at best is confusing and at worst can cause problems if fleetd is
accidentally started up somewhere it shouldn't be and starts doing work
undesirably.
This was already fixed by another commit which made it backwards
incompatible if anyone happened to be invoking fleetd with arguments,
arguably in that case they were doing it wrong anyway
(since fleetd would just ignore them) and so this provides better behaviour.
The current patch just improves the Usage message.
Commit-log-by: Jonathan Boulle <jonathanboulle@gmail.com>
=> fleetd: improve usage message with fleetd description

fleetctl/journal.go
This adds the --output flag to journal, which is passed through
to journalctl, so that you can specify its output format.
Fixes #1398
Improved-by: Djalal Harouni <djalal@endocode.com>
=> fleetctl: add -output to journal

fleetctl/destroy.go
fleetctl used to ignore requests to destory units which do not actually exist.
This behaviour was changed by commit 9530eed, restore the older behaviour by calling findUnits()
to get the right list of units.
This fixes: https://github.com/coreos/fleet/issues/1383
=> fleetctl: on destroy command ignore units that do not exist

build, build-docker, build-env, functional/.gitignore, functional/README.md, functional/Vagrantfile, functional/clean.sh, functional/config.rb, functional/platform/nspawn.go, functional/provision/install_go.sh, functional/run-in-vagrant, functional/start_etcd, functional/test, functional/user-data
=> [WIP] test: added test scripts for the functional tests

client/http.go, fleetctl/destroy.go, fleetctl/destroy_test.go, fleetctl/fleetctl.go, fleetctl/fleetctl_test.go, fleetctl/stop_test.go, fleetctl/unload_test.go
fleetctl destroy fix and more tests. It contains a follow up fix for the race condition that was discussed in this merged PR: https://github.com/coreos/fleet/pull/1417
=> fleetctl: destroy fix and more tests

Documentation/architecture.md, Documentation/deployment-and-configuration.md
/cc @jonboulle 
This wiki page is outdated http://www.freedesktop.org/wiki/Software/systemd/dbus/
Polkit rule was already implemented in this PR: https://github.com/coreos/coreos-overlay/pull/1579
=> docs: remove D-Bus and polkit note, it is not true.

build
Currently running ./build or ./test on hosts without go, gives the
confusing message:
build-env: line 3: go: command not found
build-env: line 20: go: command not found
./build: line 17: [: =: unary operator expected
Not on Linux - skipping fleetd build
Building fleetctl...
./build: line 25: go: command not found
Improve this by just:
build: can not find go binaries, Aborting.
=> build: check for go binaries and print a better error message

README.md, functional/README.md, functional/provision/install_qemu_on_semaphoreci.sh, functional/provision/install_vagrant_on_semaphoreci.sh, functional/run-in-qemu, functional/run-in-vagrant, functional/user-data
/cc @jonboulle 
Can you configure semaphoreci with the commands below?
setup: `./functional/provision/install_qemu_on_semaphoreci.sh`
run tests: `sudo ./functional/run-in-qemu`
=> tests: Added run-in-qemu script for functional tests

fleetctl/destroy_test.go, fleetctl/stop_test.go, fleetctl/unload_test.go
If the tests fail then return, and avoid printing other confusing error messages
=> fleetctl:test: {destroy|stop|unload} if the test fails then return as early as possible

functional/provision/install_qemu_on_semaphoreci.sh
Sometimes Ubuntu has problems starting upstart services
https://bugs.launchpad.net/ubuntu/+source/upstart/+bug/1367214
This fix implements workaround
/cc @jonboulle @tixxdz
=> tests: Fix kvm kernel module bug at semaphoreci

functional/cluster_test.go, functional/node_test.go, functional/scheduling_test.go, functional/unit_action_test.go
If functional tests fail in Fleetctl() start for some units, then just print directly as much information as possible. This will save some time when errors are just obvious ones.
=> fleet:functional-test: make Fleetctl() start print stdout and stderr on failures

fleetctl/fleetctl.go, fleetctl/fleetctl_test.go, fleetctl/load.go, fleetctl/start.go, fleetctl/stop.go, fleetctl/unload.go
This patches set aims to make the code more consistent and robust. It does not change the current behaviour just improves the code, consolidate it, more debug logs and code comments.
The main goal is to let stop, start, load and unload to share the same code base and probably avoid any corner case or bug that may related to one of these commands.
* Some logic can be easily shared later when we add stop to destroy command to solve  https://github.com/coreos/fleet/issues/1000  
* There were some TODOs in the code base that I cleaned up with the last two patches. These patches will make it easy for us to implement later https://github.com/coreos/fleet/pull/1295
=> fleetctl: {load|unload|start|stop} and get unit code cleanups

fleetctl/destroy_test.go, fleetctl/fleetctl_test.go, fleetctl/load_test.go, fleetctl/start_test.go, fleetctl/stop_test.go, fleetctl/unload_test.go
Patch 1: This is a preparation patch for the next start test patch that will try to create and start units from a template unit.
Patch 2: improve the start test and make sure that it handles templates
=> fleetctl:test: improve the start test and make sure that it handles templates

functional/clean.sh
functional-test.log should be functional-tests.log with (s)
=> functional-tests:clean: fix a typo in the functional-tests.log filename

functional/run-in-qemu
With these changes, users are now able to override channel name
as well as the local ssh port number. For example:
```
$ COREOS_SSH_PORT=2245 COREOS_CHANNEL=alpha ./run-in-qemu
```
Additionally BASE_IMAGE should be set according to the channel name,
to avoid potential file naming conflicts.
This PR depends on https://github.com/coreos/fleet/pull/1476
/cc @kayrus
=> functional: allow ssh port number and channel name to be overridden

functional/test
in case when you run several tests inside one VM you'd probably see lots of `ssh-agent`'s
/cc @jonboulle @antrik @tixxdz
=> tests: kill ssh-agent on exit

fleetctl/submit_test.go
Introduce a new test for the fleetctl submit command,
not only for simple units, but also for template units.
NOTE: this PR depends on #1466, which is still pending.
=> fleetctl:test: add a new test for submit command

fleetctl/destroy.go, fleetctl/destroy_test.go, fleetctl/load.go, fleetctl/load_test.go, fleetctl/start.go, fleetctl/start_test.go, fleetctl/stop.go, fleetctl/stop_test.go, fleetctl/submit.go, fleetctl/unload.go, fleetctl/unload_test.go
If no unit name is given for fleetctl commands like destroy, load,
start, stop, submit, and unload, then return with exit code 0,
printing out a soft warning message to stderr.
Fixes: #1443
/cc @kayrus @tixxdz @jonboulle
(A new revision of #1461)
=> fleetctl: check for empty input unit strings

agent/agent.go, agent/reconcile.go, agent/unit_state.go, agent/unit_state_test.go, api/server.go, engine/engine.go, fleetd/fleetd.go, functional/shutdown_test.go, functional/util/config.go, heart/monitor.go, machine/coreos.go, pkg/reconcile.go, pkg/reconcile_test.go, server/monitor.go, server/server.go, unit/generator.go
Retry of https://github.com/coreos/fleet/pull/1452 , because Semaphore.
=> server: fix panic on graceful shutdown

functional/util/util.go
When string has multiple sequenced tabs, SplitN recognized tab as a column, not separator.
quick explanation is here: https://play.golang.org/p/yfLpvycQEk
fixes status detection here: https://github.com/endocode/fleet/commit/a9dca463494251d286035cbb7da991dcad839dc4
/cc @jonboulle @tixxdz
=> tests: fixed multiple sequenced tabs recognition

functional/fixtures/units/hello@.service, functional/platform/cluster.go, functional/platform/nspawn.go, functional/tunnel_test.go, functional/util/config.go, ssh/ssh.go
adding tests which will cover #565 #1425 #1455
closes #1484
=> tests: added "fleetctl --tunnel" tests

functional/fixtures/units/metadata@.service, functional/metadata_test.go, functional/util/config.go, registry/job.go, registry/unit.go, unit/unit.go, unit/unit_test.go
Covers https://github.com/coreos/fleet/issues/1446
=> tests: added template + metadata functional test

job/job.go, job/job_test.go, registry/job.go, registry/unit.go, unit/unit.go, unit/unit_test.go
Resolves #1514
The problem was caused by the [code optimization](https://github.com/coreos/fleet/pull/1376). Before that each unit was stored in its own variable. Then this code was optimized and units became stored in hash map (`getAllUnitsHashMap`). Each hash was assigned to the unit's pointer. And when template unit was checked by `requirements()` function, its content was modified by `values[i] = unitPrintf(v, *uni)` code. Once templated unit was modified, all related units (which have same hash) were modified too, because they are related to one pointer.
Now we don't modify source contents.
=> *: fixed broken template and metadata

functional/node_test.go, functional/shutdown_test.go
Diagnostic commands such as `systemctl status` don't need elevated
permissions.
One notable exception is `journalctl`, which is actually privileged
(when accessing system journals), as it might reveal sensitive
information...
=> Cleanup: functional tests: Drop gratuitous `sudo` from various commands

ssh/known_hosts.go, ssh/ssh.go
Retrieve remote host Key Algorithms from known_host if they are there
and use them to perform ssh handshake. Otherwise fallback to default
values suggested by remote.
This patch is based from a previous patch written by:
kayrus <kay.diam@gmail.com>
Resolves #1526 and coreos/bugs#1186
=> ssh: define the list of Key Algorithms of remote hosts before handshake

build-aci
supersedes #1549
* since actool started to support --owner-root flag ([v0.7.1](https://github.com/appc/spec/commit/d26e9449fdc4533dcf16e25fdb6d5f616fa4436c))
we can use it to create tar archive with the root owned files.
* added bash trap instead of rm -rf $tgt
* added double quotes to protect aci filename when user passes
tag with the whitespaces
/cc @tixxdz @jonboulle
=> build-aci: improved build-aci script

api/server.go, fleetd/fleetd.go, functional/server_test.go, server/server.go
So far fleetd has lost its existing listeners after receiving SIGHUP.
That happened because ``reconfigure()`` simply killed the server and started
a fresh one, without taking consideration into the existing listeners.
That resulted in a strange error like:
>  Failed serving HTTP on listener: @ accept unix @: accept: invalid argument
So let's keep the list of existing listeners before killing the server,
and give it to the new server.
Fixes: https://github.com/coreos/fleet/issues/1190
/cc @kayrus @dalbani
=> fleetd: keep a list of listeners across reconfiguring fleetd

functional/server_test.go
Remove the sleep call that allowed us to produce reliable tests, it
turns out it may fail in rare cases. I suspect this due to journald
delays and how things are serialized and started when running the test.
Instead, start a normal unit then unload it to reproduce a real behaviour
then follow up with the SIGHUG on fleetd.
If the "Reloading configuration" message do not show up on the logs, then
we do not fail since the signal was received and processed, instead
continue with the "list-units" check, if it succeed then the test should have
passed at this point. However, we continue and check the logs that we ignored
previously since the test also checks for the
"Failed serving HTTP on listener" which informs us that fleetd failed.
So we check the logs again if we find them we proceed with …
=> functional: improve TestReconfigureServer test

functional/platform/cluster.go, functional/platform/nspawn.go, functional/unit_action_test.go, functional/util/util.go
In order to make functional tests cover more fleetctl commands, do the following:
* define ``util.UnitFileState`` for handling output of list-unit-files
* aadd new cluster operations ``WaitForNUnits`` and ``WaitForNUnitFiles``, wrappers based on ``util.WaitForState``.
* introduce a new test ``TestUnitCat`` for "``fleetctl cat``".
* introduce a new test ``TestUnitStatus`` for "``fleetctl status``".
* improve an existing test ``TestUnitSubmit``.
* introduce a new test ``TestUnitLoad`` for ``fleetctl load``.
=> functional: more fleetctl unit action tests

functional/unit_action_test.go, registry/job.go
Optimize Units() call when we fetch and process Jobs and Units from etcd.
We tested this with 500 services on 3 nodes where previously it would take the fleetctl client to get the list of units from fleet and etcd ~4secs  to now ~0.9secs.
Actually this will discharge fleet from doing extra sorting logic and two extra loops at the same process. One thing to note is that we request etcd to sort the Job Units for us, so I removed it from fleet, and it seems it is the same sorting logic.
=> fleetd:registry: improve Units() performance remove extra loops when fetching Jobs list from etcd

ssh/proxy.go
Hello there. We recently ran into a problem where we were not able to do proper connection handling across ssh tunnels. It turned out that this was partially caused by some buggy code on our side in combination with the things being fixed here in this PR. In case ssh sessions are created, we need to make sure to close them properly even in error cases. The fix proposed here works for us. What do you guys think? Thanks to @zeisss helping out debugging and fixing this issue.
=> ssh: Do not leak ssh sessions on errors

functional/unit_action_test.go
Make ``TestUnit{Submit,Load,Start}()`` capable of testing multiple units. After launching multiple units for activation, they become deactivated via correspondent commands: ``"submit"`` and ``"destroy"``, ``"load"`` and ``"unload"``, ``"start"`` and ``"stop"`` are coupled respectively. These are based on a common function ``doMultipleUnitsCmd()`` to be used by different tests.
This PR depends on #1544.
=> functional: support testing multiple units

functional/node_test.go, functional/platform/nspawn.go, functional/util/util.go, heart/heart.go, registry/interface.go, registry/machine.go, server/server.go
Detect the existing machine ID when fleetd starts up, to avoid uncomfortable errors when creating multiple machines in a cluster. In addition to the fix in fleetd, this PR also contains a functional test to cover such a case.
Functional test was suggested by @antrik .
/cc @wuqixuan 
Based on https://github.com/coreos/fleet/pull/1288
Fixes: https://github.com/coreos/fleet/issues/615
See also https://github.com/coreos/fleet/issues/1241
=> fleetd: detect the existing machine ID

api/units.go, fleetctl/fleetctl.go, fleetctl/load.go, fleetctl/start.go, fleetctl/submit.go, functional/fixtures/units/replace-sync.service, functional/unit_action_test.go, functional/util/util.go, registry/job.go, unit/unit.go
This PR allows units to be replaced with "submit", "load" and "start" commands. Just add the new "--replace" switch.
The previous discussion was about overwrite in this PR https://github.com/coreos/fleet/pull/1295
This PR tries to fix: https://github.com/coreos/fleet/issues/760
=> fleet: add replace unit support

fleetctl/fleetctl.go
If the unit in the registry is different from the one that is on disk,
and the user did not provide the '--replace' switch flag, then instead
of just printing a warning, let him know about the 'replace' flag.
Closes: https://github.com/coreos/fleet/issues/614
=> fleetctl: inform the user about the '-replace' switch in case the units differ

functional/unit_action_test.go
To reduce time spent during unit actions, especially ``"fleetctl {load,start} --replace"``, do some optimizations:
* combine ``replaceUnitCommon`` with ``replaceUnitMultiple``
* refactor ``replaceUnitCommon`` to improve test speed
* refactor ``unitStartCommon``
* reduce number of replaced units for tests
=> functional: reduce time spent during unit actions

functional/connectivity-loss_test.go
``TestSingleNodeConnectivityLoss`` sometimes fails with the following error:
>  FAIL: TestSingleNodeConnectivityLoss (26.50s)
>  connectivity-loss_test.go:98: Failed listing unit files: exit status 1
>  connectivity-loss_test.go:210: Units not in expected state after restoring connectivity.
This is because the test runs ``checkExpectedStates()`` only once, without retrying to check the states repeatedly. While the test had already made use of ``util.WaitForState()`` earlier in the test by itself, it actually does not call ``util.WaitForState`` after being reattached to etcd. Fix it by using ``util.WaitForState()`` correctly to avoid such occasional errors, especially on semaphoreci.
/cc @tixxdz @kayrus
=> functional: retry to check states also after connectivity got alive

job/job.go, job/job_test.go
Support truthy values in boolean unit options(true, yes, on, 1, t).
Originally written by @wuqixuan
Supersedes https://github.com/coreos/fleet/pull/1271
Fixes: https://github.com/coreos/fleet/issues/1108
=> fleetctl: support truthy values in boolean unit options

fleetctl/fleetctl.go, pkg/lease/etcd.go, registry/etcd.go, registry/job.go, registry/job_state.go, registry/machine.go, registry/unit.go, registry/unit_state.go, registry/version.go, server/server.go
As etcd's ``keysAPI`` already supports ``HeaderTimeoutPerRequest``, fleet should not handle request timeout on its own, but just pass on the timeout value to the etcd client. For that, set timeout only in ``etcd.Config.HeaderTimeoutPerRequest``, and get rid of internal timeout handling from both ``EtcdRegistry`` and ``LeaseManager``.
Suggested-by @jonboulle 
Partially resolves https://github.com/coreos/fleet/issues/1397
=> registry: use etcd.Config.HeaderTimeoutPerRequest instead of internal timeout

fleetctl/stop.go, fleetctl/unload.go
``Fleetctl stop`` or ``unload`` has been always printing out somewhat ambiguous messages like below:
```
Unit app.service loaded on 0eb1b9b6.../coreos1
```
For better usability, print out a better result message, either about stopping (or unloading) successfully, or failing to do.
Partially resolves: https://github.com/coreos/fleet/issues/1432
/cc @kayrus @tixxdz
=> fleetctl: print out result message explicitly

functional/platform/nspawn.go
Since CoreOS alpha (1000), coreos-cloudinit doesn't seem to watch
on ``/media/configdrive/openstack/latest/user_data``. That's why
functional tests haven't been running, as systemd-nspawn container
runs without any configurations.
Fix it by changing into ``/var/lib/coreos-install/user_data``.
Fixes: https://github.com/coreos/fleet/issues/1532
/cc @kayrus
=> functional: fix path to user_data to /var/lib/coreos-install

functional/platform/nspawn.go
So far ``ReplaceMember`` has been checking for error, by looking up an explicit string ``"Success"`` in stderr from ``"systemctl -M <ID> poweroff"``. However, with systemd v229 or newer, systemctl poweroff does not print out ``"Success"`` even if poweroff succeeded. This causes ``TestKnownHostsVerification`` to always return error like:
```
--- FAIL: TestKnownHostsVerification (2.66s)
client_test.go:60: Failed replacing machine: poweroff failed:
```
Fix it by changing the systemctl call to ``"machinectl poweroff <ID>"``, which should return error correctly. This would be better in the long run, than checking for messages in stderr.
Fixes: https://github.com/coreos/fleet/issues/1586
=> functional: poweroff machine using machinectl instead of systemctl

functional/run-in-qemu
Allow run-in-qemu to run with a given custom base image, e.g. ``coreos_developer_qemu_image.img`` which was built by CoreOS SDK.
```
$ ./run-in-qemu -c alpha -i ~/.qemu/coreos_developer_qemu_image.img
```
/cc @kayrus
=> functional: allow run-in-qemu to run based on a custom base image

functional/platform/nspawn.go
As systemd v230 or newer requires ``/etc/machine-id`` on a nspawn container, we need to write the container's own machine ID into ``/etc/machine-id``. Otherwise, functional tests don't start at all like:
```
--- FAIL: TestKnownHostsVerification (10.80s)
client_test.go:36: unable to detect machine PID
```
Fixes: https://github.com/coreos/fleet/issues/1594
See also https://github.com/systemd/systemd/pull/3014
See also https://github.com/coreos/rkt/pull/2440
=> functional: write machine ID into nspawn container

functional/platform/nspawn.go
As CoreOS requires PAM configurations starting from v104x, PAM configurations on the host need to copied into the nspawn container. Otherwise, every sudo command fails with messages like:
```
--- FAIL: TestShutdown (1.99s)
shutdown_test.go:43: exit status 1
```
Fixes: https://github.com/coreos/fleet/issues/1591
See also https://coreos.com/blog/security-brief-coreos-linux-alpha-remote-ssh-issue.html
=> functional: copy PAM configurations into nspawn containers

Documentation/unit-files-and-scheduling.md, agent/reconcile_test.go, agent/state.go, agent/state_test.go, api/units.go, api/units_test.go, engine/reconciler.go, fleetctl/fleetctl_test.go, functional/fixtures/units/replace.0.service, functional/fixtures/units/replace.1.service, functional/scheduling_test.go, job/job.go, job/job_test.go
Introduce a new option ``'Replaces'`` in X-Fleet the section, to get an existing unit rescheduled to another machine. This option basically works like an existing option ``'Conflicts'``, except that circular replaces in 2 units are not allowed. Also ``Conflicts`` cannot be used together with ``Replaces``, ``Global`` cannot be used together with ``Replaces``.
Fixes: https://github.com/coreos/fleet/issues/1394
/cc @onlyjob @kayrus @tixxdz
=> fleetd: introduce Replaces option in unit files

functional/fixtures/units/replace-sync.service
We should shorten the interval between the old unit and new unit, so that across ``"fleetctl start --replace"`` the old unit's ExecStopPost doesn't overlap with the next unit's ExecStartPre directive. This workaround is necessary to (hopefully) avoid occasional conflicts like:
```
unit_action_test.go:711: Did not find 1 unit in cluster, unit replace
failed: failed to find 1 active units within 15s (last found: 0)
```
Although this change doesn't completely solve underlying issues between systemd and fleet, it can reduce the number of failures.
=> functional: shorten interval for replace serialization

build, build-env, functional/test
VERSION should be defined in ``build-env``, not in individual scripts like ``build`` or ``functional/test``. Otherwise, a simple change in one of the scripts could cause unexpected version mismatch failures during functional tests.
I stumbled across this issue while rebasing giantswarm's gRPC branch on top of master.
/cc @hectorj2f
=> build: move definition of $VERSION to build-env

scripts/genproto.sh
A new script ``genproto.sh`` generates all fleet protobuf bindings under ``./protobuf/``. This requires a native protoc v3.0 or higher, gogo/protobuf with commit c3995ae4. Protoc also needs to run with explicit options, such as --proto_path and --gogofast_out.
This script is originally taken from etcd's scripts/genproto.sh.
/cc @hectorj2f
=> scripts: new script genproto.sh for generating protobuf

scripts/schema-generator
As fleet doesn't rely on Godeps any more, schema-generator should also run without dependencies on Godeps, or any string substitution.
=> scripts: remove dependencies on obsolete Godeps

functional/scheduling_test.go
In TestScheduleOneWayConflict, after destroying conflicts-with-hello.service, we need to sleep shortly to avoid occasional errors of conflicts-with-hello.service being rescheduled even after being destroyed. In that case, the conflicts unit remains active, while the original
hello.service remains inactive. Then the test TestScheduleOneWayConflict fails at the end with a message "Incorrect unit started". This error seems to occur frequently when enable_grpc turned on.
This sleep is just a workaround. We should find out the long-term solution.
Also note that, before commit 8cfc189e ("Functional tests: Fix race condition in TestScheduleOneWayConflict()"), this error didn't occur, because there was already a sleep for 5 seconds in place. However, the commit 8cfc189e tried to fix a race using …
=> functional: sleep shortly to avoid errors in TestScheduleOneWayConflict

functional/config.rb, functional/run-in-qemu
Increase RAM of test VM from 512MB to 1024MB, to fix build errors when compiling packages like ``github.com/ugorji/go``, which will be needed in the future for dependencies. Without this change, build with go 1.6 or higher fails like that:
```
github.com/ugorji/go/codec: /home/core/go/pkg/tool/linux_amd64/compile: signal: killed
```
=> functional: increase RAM to 1024MB to fix build errors

scripts/genproto.sh
As ``gogo/protobuf`` was updated to generate grpc.SupportPackageIsVersion3 by default, ``genproto.sh`` needs to be also updated.
See also https://github.com/coreos/etcd/pull/5703
=> scripts: use latest gogo/protobuf for proto files

systemd/manager.go, vendor.manifest, vendor/github.com/coreos/go-systemd/activation/listeners.go, vendor/github.com/coreos/go-systemd/dbus/dbus.go, vendor/github.com/coreos/go-systemd/dbus/methods.go, vendor/github.com/coreos/go-systemd/dbus/methods_test.go
resolves #478. Code works with these systemd changes: https://github.com/endocode/systemd/commit/5b4452a643d924015ed25972d071ad8802aad29c
Otherwise fleet will fallback to the normal `ListUnits` method.
I don't like this code: https://github.com/endocode/fleet/blob/9828ed19752bdaae167d79e458fd7200ca3cb305/systemd/manager.go#L248
Instead of calling several times for each unit's status I'd like to implement new method called `GetUnitsProperties`
This PR contains godeps diffs only for test purposes. These changes are also introduced in go-systemd repo: https://github.com/coreos/go-systemd/pull/150
/cc @jonboulle @tixxdz @antrik
=> fleetd: get filtered list of units instead of all units

.travis.yml, build-env
Allow travis to build fleet also with the most recent go compiler, "tip".
For example, as of 2016-06-22, go "tip" compiler's version is ``"devel +1f44643 Wed Jun 22 00:12:55 2016 +0000"``.
To make it work, build-env needs to be also updated, not to exit with error in case of the devel version.
=> travis: add tip to the compiler and update build-env.

Documentation/unit-files-and-scheduling.md, agent/reconcile.go, agent/state.go, agent/state_test.go, api/units.go, api/units_test.go, engine/state.go, fleetctl/fleetctl_test.go, functional/fixtures/units/conflict-global.0.service, functional/fixtures/units/conflict-global.1.service, functional/scheduling_test.go
Support ``Conflict`` flag in global units, by allowing ``Conflict`` in metadata format, as well as allowing agent reconciler to check if a global unit has conflicts.
This PR is based on #1270 that was originally written by @wuqixuan, On top of that, I also implemented a small fix in agent reconciler, as well as a new functional test ``TestScheduleGlobalConflicts``.
Fixes: https://github.com/coreos/fleet/issues/1109
Supersedes: https://github.com/coreos/fleet/pull/1270
=> fleetd: support conflict in global unit

pkg/reconcile.go, server/server.go
To avoid potential nil-dereferences in agent reconciliation, check that eStream is available before accessing to ``eStream``. Otherwise, just return.
Example error logs:
```
ERROR server.go:192: Server register machine failed: 105: Key already exists
(/_coreos.com/fleet/machines/d5ca2e9d4039e480807464280c9ab4a2/object) [203153266]
INFO server.go:188: hrt.Register() success
INFO server.go:198: Starting server components
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4bc024]
goroutine 49 [running]:
panic(0xc06080, 0xc82000a0a0)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/fleet/pkg.(*reconciler).Run.func1(0xc8201cef00, 0xc8201b9560, 0xc8201cf2c0)
/opt/fleet/gopath/src/github.com/coreos/fleet/pkg/reconcile.go:65 …
```
=> fleetd: check that eStream is available before accessing to that

functional/run-in-qemu
CoreOS has changed GPG keys for new releases. If we don't use `48F9B96A2E16137F` here and there is already imported old GPG key, it will be not updated and GPG check will fail.
=> test: Updated GPG pub key ID

functional/client_test.go, functional/cluster_test.go, functional/connectivity-loss_test.go, functional/fleetctl_test.go, functional/node_test.go, functional/platform/nspawn.go, functional/scheduling_test.go, functional/server_test.go, functional/shutdown_test.go, functional/unit_action_test.go
Make every call ``cluster.Fleetctl()`` (or ``run()``) return both ``stdout`` and ``stderr``, to get them included in the result error buffer. We need to do this to make sure that every potential error message is printed out. This change will help us investigate occasional failures in functional tests.
=> functional: retrieve stdout/stderr after running command

fleetctl/destroy.go, fleetctl/stop.go, fleetctl/unload.go
Destroy logic was already [improved](https://github.com/coreos/fleet/commit/ad702480e3a5a404690396d6c6b5e6c8c5d486f4) so this issue could be closed: https://github.com/coreos/fleet/pull/1256
https://github.com/coreos/fleet/issues/710
But we still have to print some kind of error message when units were not found.
=> fleetctl: print error when units were not found in registry

config/config.go, fleetd/fleetd.go, functional/systemd_test.go, server/server.go, systemd/manager.go
Hi! I am looking at using fleet to manage a handful of machines with ssh access but without root access.
It might be a far shot or a misguided idea: please let me know if this is a dead-end.
If this is interesting I added 2 options to fleetd's configuration file to support that:
```
units_dir=/home/vagrant/fleetunits
systemd_user=true
```
On archlinux, I can deploy `example/hello.service` but I get
`AgentReconciler task failed: type=LoadUnit job=hello.service reason="unit scheduled here but not loaded" err=No such file or directory`.
Some debugging shows that it comes from dbus's call to `LinkUnitFiles`; I have not figured out which folder it tries to link into yet.
Thanks for your attention.
=> Support for targeting `systemd --user`

functional/user-data
In etcd config, increase ``heartbeat-interval`` from 100 to 600, also ``election-timeout`` from 1000 to 6000. This is a workaround for avoiding occasional failures of ``TestSingleNodeConnectivityLoss`` like below:
```
--- FAIL: TestSingleNodeConnectivityLoss (41.41s)
connectivity-loss_test.go:98: Failed listing unit files:
stdout:
stderr: Error retrieving list of units from repository:
googleapi: Error 503: fleet server unable to  communicate with etcd
err: exit status 1
```
See also https://github.com/coreos/fleet/issues/1289#issuecomment-146424680
Workaround for https://github.com/coreos/fleet/issues/1250
=> functional: tune intervals in etcd config to avoid connectivity errors

fleetctl/fleetctl.go
``Fleetctl`` has not been able to make use of environment variables such as ``FLEETCTL_ENDPOINT``, because of a missing call to ``getFlagsFromEnv()``. That was a regression from commit 848d3561 ``("fleetctl: convert cli to cobra")``.
Fix it by calling ``getFlagsFromEnv()`` again based on ``spf13/pflag`` instead of the native flag.
Reported by @odolbeau.
Fixes https://github.com/coreos/fleet/issues/1631
=> fleetctl: reenable support for environment variables

Documentation/deployment-and-configuration.md, Documentation/using-the-client.md, config/config.go, fleet.conf.sample, fleetd/fleetd.go, server/server.go
Expose ``username`` and ``password`` as options for configuration to etcd endpoints.
Originally written by @jipperinbham.
Fixes https://github.com/coreos/fleet/pull/1505
Supersedes https://github.com/coreos/fleet/pull/1506
=> config: add basic etcd authentication

systemd/manager.go
Let's get dbus connection directly inside ``NewSystemdUnitManager``, instead of calling a separate function ``createDbusConnection()``.
Suggested by @jonboulle.
See https://github.com/coreos/fleet/pull/1393#discussion_r70782867
/cc @hmalphettes
=> systemd: get dbus connection directly in NewSystemdUnitManager

Documentation/architecture.md
Yet another broken weblink to an etcd v2 weblink.
=> Documentation: fix a broken weblink to etcd v2 document

functional/client_test.go, functional/platform/cluster.go, functional/platform/nspawn.go
``TestFleetctlWithEnv`` runs simply fleetctl list-machines, but by setting an environment variable ``FLEETCTL_ENDPOINT``, instead of the cmdline option ``'--endpoint'``. This way functional test is able to detect regressions like https://github.com/coreos/fleet/issues/1631.
=> functional: introduce a test TestFleetctlWithEnv

.travis.yml, functional/provision/install_go.sh
A new golang 1.6.3 is available especially for a security fix.
=> travis,functional: bump golang to 1.6.3

agent/unit_state.go, agent/unit_state_test.go, registry/unit_state.go, registry/unit_state_test.go
Long time ago there were checks for nil unit hashes in ``agent.UnitStatePublisher.publishOne`` and ``registry.UnitStateToModel``, but given that units could enter the system without populated hashes, the checks were disabled: 11949e0 ``("agent: publish unit state regardless of hash")``.
However the hashes are now always populated, so the corresponding assertions should be reenabled.
Fixes https://github.com/coreos/fleet/issues/989
=> agent: reenable check for nil hash in unit state publisher

agent/agent.go, functional/systemd_test.go, systemd/manager.go, unit/fake.go, unit/manager.go
In ``Agent.unloadUnit()``, if ``systemdUnitManager.TriggerStop()`` returns any error, do not unload systemd units. Otherwise the unit could get into a state where the unit cannot be stopped via fleet, because the unit file was already removed.
Fixes https://github.com/coreos/fleet/issues/1216
/cc @patrickbcullen
=> systemd,agent: unload unit only when TriggerStop() runs successfully

fleetctl/fleetctl.go, fleetctl/start.go, functional/unit_action_test.go
To resolve inconsistency between ``"systemctl start"`` and ``"fleetctl start"``, fleetctl needs to check systemd states after starting units. If the systemd state is not a desired one, wait until it gets an active state.
Fixes: https://github.com/coreos/fleet/issues/1025
=> fleetctl: check also systemd states after starting units

fleetctl/ssh.go
Error message of fleetctl ssh should be ``"Unable to SSH to remote host"``.
Fixes https://github.com/coreos/fleet/issues/995
=> fleetctl: fix error message when fleetctl ssh fails

fleetctl/list_machines.go
Print out friendly error message when ``fleetctl list-machines`` fails. Indicate that the API isn't working correctly instead of being unavailable. Also mention the most likely culprit, which is something to do with etcd.
Note that I didn't remove the prefix ``"googleapi:"`` as suggested by the original issue, because the prefix doesn't come from fleet, but from the google API itself.
Suggested by @robszumski
Fixes https://github.com/coreos/fleet/issues/1203
=> fleetctl: print out friendly error message from fleetctl list-machines

agent/unit_state_test.go
`TestUnitStatePublisherRunWithDelays()` has not exactly initiated each service sequentially, but let it run in parallel. That's why the unit test sometimes fails with messages like:
```
--- FAIL: TestUnitStatePublisherRunWithDelays-2 (0.00 seconds)
unit_state_test.go:626: bad published UnitStates:
got []string{"0.service", "2.service", "4.service", "1.service", "3.service"},
want []string{"0.service", "1.service", "2.service", "3.service", "4.service"}
unit_state_test.go:640: bad published UnitStates:
got []string{"0.service", "2.service", "4.service", "1.service", "3.service"},
want []string{"0.service", "1.service", "2.service", "3.service", "4.service"}
unit_state_test.go:658: bad UnitStates:
got []string{"foo.service", "baz.service", "bar.service"},
want []string{"foo.service", …
```
=> agent: make TestUnitStatePublisher wait for each goroutine to finish

agent/agent.go, agent/agent_test.go, agent/task.go, systemd/manager.go, unit/fake.go, unit/fake_test.go, unit/manager.go
Now that UnitManager.{TriggerStart,TriggerStop,Unload}() could return an error, the error should be delivered up to ``mapTaskToFunc()``, not to be ignored by the task manager. Doing that, we can fix a bug in fleet ignoring failed attempt to start/stop a unit.
Fixes https://github.com/coreos/fleet/issues/998
=> agent,unit: check errors from start/stop/unload-ing unit

agent/agent.go
Improve warning message from `TriggerStop()` in case of error, because it's just a trigger, not the actual stopping.
Suggested by @jonboulle
=> agent: improve warning message in case of error after TriggerStop

Documentation/unit-files-and-scheduling.md, api/units.go, api/units_test.go
Following unit types don't support templates:
* automount
* busname
* device
* mount
* scope
* slice
* snapshot
* swap
On the other hand, only the following types are allowed for templates:
* path
* service
* socket
* target
* timer
As it's not that simple to support templates for particular unit types on systemd, reject templates for such units from the fleet side.
Fixes https://github.com/coreos/fleet/issues/1390
=> api: reject templates for particular unit types

build-env, functional/test
As gRPC is being used, we need to run functional tests once with `enable_grpc` turned off, and again with `enable_grpc` turned on.
WIP: this PR must be merged after #1426 got merged.
=> functional: run tests with enable_grpc turned both on and off

registry/rpc/registrymux_test.go, test
A new directory `registry/rpc` should be added to the list of unit tests, so that `./test` can test also unit tests under RPC registry. Without this change, even compile errors in unit tests cannot be easily detected, because the `./test` ignores the unit tests.
Actually this fix was originally included in https://github.com/giantswarm/fleet/pull/32, and as far as I can remember, it was merged correctly to https://github.com/coreos/fleet/pull/1426. But somehow it disappeared during rebases, and I just realized that. Though it's not that critical, because OTOH all the relevant fixes included in https://github.com/giantswarm/fleet/pull/32 were correctly merged. So it's just the matter of completeness.
=> test: add registry/rpc to the list of unit tests

functional/test
Just a cleanup for removing obsolete commands that have been already commented out.
Suggested by @jonboulle
=> functional: clean up obsolete commands that are commented out

.travis.yml, functional/provision/install_go.sh, test
First, for travis, add go 1.7 to the list of required go compiler versions. Now that go 1.7 was released, the list of required go compiler versions should also include go 1.7.
Also in functional tests, install go 1.7 instead of 1.6.3.
And also exclude `./gopath` also from the list for checking license headers.
=> travis,functional: add go 1.7 and exclude ./gopath

fleetctl/destroy.go
Apparently fleetctl destroy command has never supported both options `--no-block` and `--block-attempts`, although `runDestroyUnit()` tries to use the flags. Fix it by defining the options for `cmdDestroy`.
Note that it's not a regression caused by conversion into cobra. It has been just like that since the beginning. I just happened to find it out yesterday when I was working on #1664 .
=> fleetctl: support options --no-block, --block-attempts for destroy command

api/machines_test.go, api/state_test.go, api/units_test.go, engine/rpcengine.go, fleetd/fleetd.go, functional/systemd_test.go, glide.lock, glide.yaml, pkg/filesystem_test.go, systemd/manager_test.go, vendor/github.com/coreos/etcd/error/error.go
In principle we should avoid returning `err.Error()`. Instead we should just return err, to be able to inspect the error in a flexible way.
Also in `rpcRenewLeadership()` check for an exact error code from etcd, `EcodeKeyNotFound`, instead of comparing error string with a particular string pattern. Doing that, we can also avoid using `err.Error()`.
=> *: avoid using err.Error()

build, fleetd/fleetd.go, main.go
So far it hasn't been possible to do `"go get github.com/coreos/fleet"` because there was no main.go in the top source directory. Create main.go, a simple wrapper for fleetd to make it _"go-getable"_.
This is a preparation for https://github.com/coreos/fleet/issues/1665, as `goaci` requires a go-getable package.
=> fleetd,main: make github.com/coreos/fleet go-getable

Documentation/rkt_guide.md
Apparently rkt doesn't support a single dash in its option any more. For example, `"rkt -volume"` doesn't work any more. Use double dash instead: `"rkt --volume"`
Also `--insecure-skip-verify` doesn't exist. Use `--insecure-options=image` instead.
=> Documentation: fix unavailable rkt options in examples

fleetctl/fleetctl.go, fleetctl/load.go, fleetctl/start.go, fleetctl/stop.go, fleetctl/unload.go
It's not appropriate to check systemd active states with DBUS connection, as that will return correct states only on the same machine. So we should also introduce a check using `cAPI.UnitStates()`, to check states on other machines.
=> fleetctl: check systemd active state via client API

fleetctl/fleetctl.go, registry/job.go
* registry: make `CreateUnit()` explicitly return error
: When `marshal()` returns a non-nil error `'err'`, which shadows the pre-defined `'err'`, we should explicitly return the second error returned from `marshal()`. Otherwise it will always return `nil`. To fix other potential errors, let's just return `err` explicitly. This was discovered by running "go tool vet":
```
$ go tool vet --shadow ./registry
registry/job.go:316: declaration of "err" shadows declaration at registry/job.go:315
```
* fleetctl: fix wrong error value from `matchLocalFileAndUnit()`
: In `matchLocalFileAndUnit()`, if `os.Stat()` returns nil and `getUnitFromFile()` returns non-nil error, then in the end `matchLocalFileAndUnit()` will return `(false, nil)`. That's not the expected result. It should have returned the …
=> registry,fleetctl: fix bugs regarding shadowed error variables

Documentation/rkt_guide.md
Fix weblink to build-aci to
https://github.com/coreos/fleet/blob/master/scripts/build-aci.
This was a side-effect of moving the script to the scripts directory.
=> Documentation: fix a broken weblink to scripts/build-aci

registry/rpc/registrymux_test.go, ssh/known_hosts_test.go
Run `TestRegistryMuxUnitManagement()` only when user's euid is 0 and systemd is available at run-time. Such a distinction is necessary for avoiding test failures, especially when unit tests run on travis CI, where systemd is not available. With those checks, we can re-enable error handling after calling `systemd.NewSystemdUnitManager()`.
Besides fix also a hidden bug in `TestWrongHostKeyFile()` to skip the test on Linux if euid is 0. On Linux `syscall.Setuid()` is not supported in go. So running unit tests with root privileges fails when calling Setuid.
=> registry/rpc: re-enable error handling after NewSystemdUnitManage

functional/node_test.go, functional/platform/cluster.go, functional/platform/nspawn.go
Since systemd v231, `TestNodeShutdown` fails with the following message.
```
--- FAIL: TestNodeShutdown (fleet.conf=[enable_grpc=false]) (8.98s)
node_test.go:83: Unit hello.service not reported as inactive:
```
It's because of behavioral change of `"systemctl status"`. Until systemd v230, `"systemctl status hello.service"` has printed
```
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)
```
to stdout, when hello.service is not active. So the functional test `TestNodeShutdown` has expected a string `"Active: inactive"` in the message from stdout.
Since systemd v231, however, the output string has become
```
Unit hello.service could not be found
```
And it's printed to stderr, instead of stdout.
As `MemberCommand()` doesn't return stderr at all, we need to make …
=> functional: fix error from message change from systemctl status

Documentation/unit-files-and-scheduling.md, functional/fixtures/units/discovery.service, functional/install_test.go, systemd/manager.go
Introduce a section `[Install]` in unit files, to allow `WantedBy` in the section to be able to enable the dependent units.
This PR is just a rebased version of https://github.com/coreos/fleet/pull/1523, except for minor changes to fix build errors.
Resolves https://github.com/coreos/fleet/issues/1382
Supersedes https://github.com/coreos/fleet/pull/1523
/cc @kayrus
=> fleetd: process dependencies in [Install] section

agent/reconcile_test.go, agent/state.go, engine/reconciler.go, engine/scheduler.go, functional/fixtures/units/replace-kick0.service, functional/fixtures/units/replace.2.service, functional/scheduling_test.go, job/job.go
So far in engine reconciler, `decide()` returns a bool variable to determine whether it's possible to schedule or not. Reschedule was not handled in a proper way.
So let's create a new tri-state for `job.JobAction`, i.e. `JobActionSchedule`, `JobActionUnschedule`, and `JobActionReschedule`. And return the tri-state variable instead of bool. That way `AbleToRun()` can check return values from `HasConflict()` and `HasReplace()` in a correct manner.
With that, we can fix bugs in rescheduling for replaced units. While the `'Replaces'` option has been supported since https://github.com/coreos/fleet/pull/1572, the engine didn't actually unschedule units to be replaced. It was a bug.
So let's implement `GetReplacedUnit()` to expose the replaced unit from `AgentState` to the engine reconciler. …
=> agent,engine: fix bugs in rescheduling for replaced units

api/state.go, client/api.go, client/http.go, client/registry.go, fleetctl/fleetctl.go, protobuf/fleet.pb.go, protobuf/fleet.proto, registry/fake.go, registry/interface.go, registry/rpc/inmemory.go, registry/rpc/inmemory_test.go, registry/rpc/registrymux.go, registry/rpc/rpcregistry.go, registry/rpc/rpcserver.go, registry/unit_state.go, registry/unit_state_test.go, schema/v1-gen.go, schema/v1-json.go, schema/v1.json
- api: support `GET` method for `stateResource`
- schema: introduce `Get` method for `UnitState`
- client: introduce `UnitState()` for API interface
- protobuf: define `GetUnitState()` for registryClient and registryServer
- registry: introduce `UnitState()` for `etcdRegistry` and `RPCRegistry`
- fleetctl: replace `cAPI.UnitStates()` with `.UnitState()`
- registry: add new unit tests for `GetUnitState()` and relevant ones
- fleetctl: periodically check for systemd states using `waitForState`
- fleetctl: make use of `waitForState` also in `assertUnitState()`
Fixes https://github.com/coreos/fleet/issues/1675
=> api: support cAPI.UnitState() for a single unit

functional/connectivity-loss_test.go, functional/node_test.go, functional/platform/cluster.go, functional/platform/nspawn.go, functional/server_test.go, functional/shutdown_test.go, functional/unit_action_test.go
Remove `Cluster.MemberCommand()`, rename `MemberCommandStderr()` to `MemberCommand()`, and update every call site accordingly.
That way we can clean up leftovers from https://github.com/coreos/fleet/pull/1700.
=> functional: allow MemberCommand to return stderr

Documentation/api-v1.md, Documentation/unit-files-and-scheduling.md, agent/reconcile.go, agent/reconcile_test.go, api/machines.go, api/machines_test.go, client/api.go, registry/fake.go, registry/interface.go, registry/machine.go, registry/rpc/registrymux.go, registry/rpc/rpcregistry.go
Source: https://github.com/coreos/fleet/pull/1077
=> fleetd: support dynamic metadata

api/machines.go, api/machines_test.go, functional/machines_test.go, registry/rpc/registrymux.go
To be able to merge https://github.com/coreos/fleet/pull/1642, we need to fix several things, as well as add functional tests.
* registry/rpc: call etcdRegistry.MachineState() for every case
* api: get Value embedded as members in struct
* functional: add new machine tests for dynamic metadata
Depends on https://github.com/coreos/fleet/pull/1642. I'll first merge #1642, and after that, I'll merge this PR.
As master branch would fail without this PR, I'm going to merge it right away.
Feel free to report possible bugs. I'll create another PR to handle them in the next week.
/cc @dalbani
=> api,functional: dynamic metadata - fix bugs and add functional tests

functional/machines_test.go, functional/metadata_test.go, functional/unit_action_test.go
Functional test seems to have a limitation of 40 tests in total. When the number of tests becomes more than 40, no more cluster member can be created, so that test ends up with hanging mysteriously. To avoid that, let's reduce number of tests, mainly for dynamic metadata tests as well as unit action tests. It's just squashing similar tests.
As go test natively has an upper limit of 600sec in total for all tests, we should reduce total running time. So let's reduce number of units to be tested in the unit state tests, and reduce maximum block attempts for the metadata template test. This will fix the failure on semaphoreci, which has suddenly appeared since the dynamic metadata tests. This should make tests work for now. In the long run, it would be necessary to be able to tune the …
=> functional: reduce number of tests and total running time

functional/platform/nspawn.go
As described in https://github.com/coreos/fleet/pull/1704, functional test has a bug hitting an upper limit of ~40 tests in total. That's actually an issue of DBUS connections remaining opened even after nspawn containers got successfully terminated. That's why the number of unix sockets grows up to 256.
```
$ netstat -nap | grep /var/run/dbus/system_bus_socket | wc -l
256
```
From that moment on, functional test hangs mysteriously. Sometimes users could see errors like `"The maximum number of active connections for UID 0 has been reached."`
Its reason is that every DBUS connection was never closed. The more tests we add, the more stale DBUS connections we have. This bug has existed since the beginning.
Fix it by adding `conn.Close()` after running systemd commands.
=> functional: close DBUS connections after running systemd commands

functional/machines_test.go, functional/metadata_test.go, functional/unit_action_test.go
This reverts commit 0f8467201adc16abe33d0f007ccafc81b5bd5858, and commit f81c3b2e9ea2df2f232c17367291e0b29ee87f0d.
So it reverts https://github.com/coreos/fleet/pull/1704.
=> Revert workaround for reducing tests

Dockerfile, scripts/build-binary, scripts/build-docker, scripts/release.sh
Add Dockerfile as well as new scripts, to be able to build Docker images to be uploaded to `quay.io/coreos/fleet`. Structure under scripts directory is similar to that of etcd.
See also https://github.com/coreos/fleet/issues/1705.
=> scripts: add scripts for building Docker images

Documentation/api-v1.md, Documentation/release.md, Documentation/rkt_guide.md
A new document `release.md` describes how to create a new release of fleet. It's derived from the same document of etcd.
Also update command-line options in `rkt_guide.md` and fix a typo in `api-v1.md` so that an example for PATCH method contains a correct prefix.
=> docs: add a release instruction document

.travis.yml, functional/provision/install_go.sh
For travis, let's use the standard latest version of each stable golang tree. For example, 1.7.x == 1.7.3, 1.6.x == 1.6.3, and 1.5.x == 1.5.4. Doing that, we are able to avoid bumping the minor version every time.
For functional tests, upgrade go from 1.7.1 to 1.7.3.
=> travis,functional: change golang versions

engine/rpcengine.go
When gRPC is turned on, `TestScheduleMachineOf` fails sometimes, as the engine becomes unreachable with the following error messages:
```
transport: http2Client. notifyError got notified that the client transport was broken EOF.
ERROR registrymux.go:166: Retry to connect to new engine: dial tcp 172.18.1.1:50059: getsockopt: connection refused
ERROR registrymux.go:166: Retry to connect to new engine: dial tcp 172.18.1.1:50059: getsockopt: connection refused
ERROR registrymux.go:166: Retry to connect to new engine: dial tcp 172.18.1.1:50059: getsockopt: connection refused
```
This must have been a regression from commit ecb121a ("registry/rpc: use simpleBalancer instead of ClientConn.State()"). Remove the additional checking with IsRegistryReady, in order to avoid the occasional case of …
=> engine: fix a bug in engine being unreachable

fleetctl/fleetctl.go
Even when `waitForState()` does not return correct states in defaultSleepTime, `"fleetctl start/stop"` works just fine, because `checkUnitState()` already waits until units got populated. So let's remove the unnecessary error message.
Use also `Debugf()` instead of `Debug()`.
Change also error messages into general ones, as it might be used in any cases for fetching unit states.
=> fleetctl: remove unnecessary error messages

agent/reconcile_test.go, agent/state.go, agent/state_test.go, functional/fixtures/units/conflict.multiple.0.service, functional/fixtures/units/conflict.multiple.1.service, functional/fixtures/units/conflict.multiple.2.service, functional/scheduling_test.go, job/job.go, job/job_test.go
So far when parsing values defined in the `Conflicts` option, it hasn't taken multiple values into account. So let's allow `j.Conflicts()` to parse multiple values, splitting with white-space delimiters into a slice of each string.
In `AgentState.HasConflict()`, split a common part for checking if a unit belongs to a Conflicts list, into a new helper `hasStringInSlice()` Also return a slice of conflicted strings, instead of a single string. Doing that, `HasConflict()` can be more readable.
Also extend unit tests and functional tests.
Fixes https://github.com/coreos/fleet/issues/1245
=> agent: allow HasConflict() to handle multiple values defined in Conflicts

fleetctl/fleetctl.go, fleetctl/restart.go, fleetctl/restart_test.go, fleetctl/status.go, functional/scheduling_test.go, functional/unit_action_test.go
This PR is _yet another_ revision of a long-running issue, `fleetctl restart` and `status` with global units.
- First allow `"fleetctl status"` to run with global units. For the purpose, implement a helper `cmdGlobalMachineState()` that filters a list of machines only with unique entries.
- Introduce a new command `"fleetctl restart"`. This part is originally taken from https://github.com/coreos/fleet/pull/1238 written by "Kyle Boorky kboorky@turbine.com", committed by @hhoover . 
- Introduce unit test and functional test for `fleetctl restart`.
- Add new tests for global tests in `TestScheduleGlobalUnits()`.
This PR is not about changing API or metadata format in etcd registry. It's not introducing any new mechanism, because I don't think I can afford changing such design at the moment. …
=> fleetctl: status and restart commands with global units

Documentation/release.md
In the release document, add a missing section about how to sign binaries with the CoreOS gpg key.
It's mainly taken from the etcd release document.
=> Documentation: describe how to sign binaries with gpg key

scripts/fleet-wrapper
This script is a wrapper for running fleet via rkt. It's supposed to be used by Ignition configs, which could fetch the script remotely to put it as e.g. `/opt/bin/fleet-wrapper`.
=> scripts: add fleet-wrapper

Documentation/deployment-and-configuration.md, Documentation/using-the-client.md
fleet is no longer shipped within Container Linux.
=> docs: remove coreos-specific wording
