functional/platform/nspawn.go, test
I don't actually know why govet won't catch this error. Any insight is appreciated.
=> functional testing fixes

Documentation/deployment-and-configuration.md
=> doc: link from config to api doc

fleetctl/fleetctl.go
This addresses half of https://github.com/coreos/fleet/issues/1171. The daemon will still need some work.
=> fleetctl: add support for etcd2's IANA ports

fleetctl/fleetctl.go, server/server.go
=> Revert "server,fleetctl: clean up duration calculation"

functional/platform/nspawn.go
These changes help make the functional tests more deterministic.
=> More functional test fixes

api/units.go, api/units_test.go, fleetctl/fleetctl.go, unit/unit.go, unit/unit_test.go
this pr additionally makes fleetctl check the error when attempting to change desired unit state.
=> check for loading/launching templates in fleet http api

Godeps/Godeps.json, Godeps/_workspace/src/github.com/godbus/dbus/LICENSE, Godeps/_workspace/src/github.com/godbus/dbus/conn.go, Godeps/_workspace/src/github.com/godbus/dbus/encoder.go, Godeps/_workspace/src/github.com/godbus/dbus/export.go
=> Update godbus/dbus godep.

fleetd/fleetd.go, pkg/flag.go, pkg/flag_test.go
=> fleetd: use a sane default set of etcd endpoints

Documentation/deployment-and-configuration.md
=> Added unit info for reconcile interval

README.md
fixes https://github.com/coreos/fleet/issues/1311
=> readme: fix kubernetes link to use http

fleetctl/destroy.go, fleetctl/fleetctl.go
in 1816c53ab58ca430914637cefc23985353b72d31 i missed a case where
checkUnitState was skipped by 'continue' in the case that the unit
exists on disk.
=> fleetctl: call checkUnitState when unit exists on disk

fleetctl/fleetctl.go
recently fleetctl started waiting for unit creation before proceeding by
checking for CurrentState == "inactive". this change caused fleetctl to
hang waiting for global units, because global units never have a
CurrentState, only a DesiredState.
fixes #1331
=> fleetctl: wait for DesiredState instead of CurrentState for global units

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/etcd/client/README.md, Godeps/_workspace/src/github.com/coreos/etcd/client/cancelreq.go, Godeps/_workspace/src/github.com/coreos/etcd/client/cancelreq_go14.go, Godeps/_workspace/src/github.com/coreos/etcd/client/client.go, Godeps/_workspace/src/github.com/coreos/etcd/client/client_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/cluster_error.go, Godeps/_workspace/src/github.com/coreos/etcd/client/fake_transport_go14_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/fake_transport_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/keys.go, Godeps/_workspace/src/github.com/coreos/etcd/client/keys_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/members_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/srv_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/pathutil/path.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/pathutil/path_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/set.go
=> Godeps: bump etcd deps

Documentation/deployment-and-configuration.md
=> Added "etcd_key_prefix" option explanation

.travis.yml
This allows tests to run on Travis's container-based infrastructure
=> *: disable sudo for travis

agent/unit_state_test.go
=> agent/unit_state: print more verbosely in failure

Documentation/fleet-scaling.md, README.md
Builds on #1306, adds a note to README
=> docs: discuss fleet maintenance/scalability

.travis.yml, agent/unit_state_test.go, functional/doc.go
Looks like this is all kinds of sad right now :(
=> Enable testing on Go 1.5

Documentation/deployment-and-configuration.md
Add some description about medadata on fleetd configuration.
Fixes #1255
=> Documentation: update fleetd configuration medadata description

Documentation/states.md
/cc @jonboulle @joshix @robszumski 
resolves https://github.com/coreos/fleet/issues/1404
=> Added unit file lifecycle in fleet

Documentation/api-v1.md, Documentation/architecture.md
/cc @joshix @robszumski @jonboulle
=> docs: Restructure links

Documentation/deployment-and-configuration.md, Documentation/using-the-client.md, fleet.conf.sample
/cc @jonboulle @joshix @robszumski 
resolves https://github.com/coreos/fleet/issues/1414
=> Added a note about API on TCP and restructured links

.travis.yml
=> Bump go versions in travis CI

functional/run-in-vagrant, functional/test
This enables running only selected tests -- and maybe other useful things too...
=> Pass on test script arguments to "go test" command

functional/test
fixes incorrect exit status here: https://github.com/coreos/fleet/pull/1481
=> tests: Fixed exit status in functional tests

functional/test
/cc @jonboulle 
I added this code for ubuntu support and it was not implemented. So let's remove.
=> tests: remove legacy code

functional/run-in-qemu
=> tests: minor improvements for run-in-qemu script

functional/README.md
/cc @jonboulle @antrik @tixxdz
=> tests: added description on how to run specific tests

Documentation/architecture.md
/cc @jonboulle @joshix @robszumski
=> docs: updated polkit/systemd information

functional/connectivity-loss_test.go, functional/fixtures/units/global@.service, functional/fixtures/units/single@.service, functional/platform/nspawn.go, functional/util/config.go, functional/util/util.go
Fixes https://github.com/coreos/fleet/issues/715
=> Add test for behaviour on etcd connectivity loss

Documentation/unit-files-and-scheduling.md
fixes https://github.com/coreos/fleet/issues/1511
cc: @kayrus @daniellowtw
=> docs: new example to highlight multiline behavior

functional/scheduling_test.go
Wait for the `destroy` command to take effect using a proper wait
condition (with `WaitForState()`), instead of a fixed sleep period --
which was sometimes insufficient, causing intermittent failure.
This fixes https://github.com/coreos/fleet/issues/1504
The condition function is mostly based on `WaitForNActiveUnits()`, with
some adjustments for the different scenario.
=> Functional tests: Fix race condition in TestScheduleOneWayConflict()

.travis.yml, build-aci, build-docker, functional/test, test, test-docker
=> build: bumped golang version in build scripts

functional/platform/nspawn.go
=> tests: move all files' writes into loop

pkg/filepath_test.go
Make sure that ParseFilepath() returned the same input since it was not
able to determin the current user or the $HOME env variable.
This fixes a bug where tests are under these conditions but at the same
time it adds unit checks for ParseFilepath() to make sure that it is
doing the right thing.
This fixes https://github.com/coreos/fleet/issues/1547
=> tests: fix TestParseFilepath where it is run under an unknown user or $HOME dir

build-aci, build-docker, test-docker
=> build: fixed docker-based scripts

Documentation/using-the-client.md
Partially addresses https://github.com/coreos/fleet/issues/975
=> Documentation: Suggest using `fleetctl ssh` with `systemctl restart`

.travis.yml, build-aci, build-docker, functional/provision/install_go.sh, test-docker
golang v1.6.2 has been released
=> build: bump golang to 1.6.2

functional/.gitignore, functional/clean.sh, functional/client_test.go, functional/cluster_test.go, functional/connectivity-loss_test.go, functional/metadata_test.go, functional/node_test.go, functional/platform/cluster.go, functional/platform/nspawn.go, functional/scheduling_test.go, functional/server_test.go, functional/shutdown_test.go, functional/test, functional/tunnel_test.go, functional/unit_action_test.go
resolves #1565
/cc @tixxdz @jonboulle @dongsupark
=> tests: added journal logs fetch feature for functional tests

functional/test, functional/util/config.go
=> tests: test fleetd with extra configuration options

functional/connectivity-loss_test.go
``TestSingleNodeConnectivityLoss`` has been so far retrieving is-enabled status by calling ``"systemctl list-unit-files UNITS"``. It was expected to get ``"enabled"`` for each unit. This has worked until systemd v227. However, that's not the case any more since systemd v228, precisely since https://github.com/systemd/systemd/commit/0ec0deaa30d0e68430f03fa6f32affa576481d18 ("install: follow unit file symlinks in /usr, but not /etc when looking for [Install] data"). Since then, systemctl list-unit-files returns ``"linked-runtime"`` status for each fleet unit, which is actually reasonable behavior for units that are not installed persistently under ``/etc/systemd``.
With systemd v228 or newer, however, ``TestSingleNodeConnectivityLoss`` in fleet functional tests cannot make use of …
=> functional: call systemctl is-enabled instead of list-unit-files

CONTRIBUTING.md
Add description about adding tests to CONTRIBUTING.md.
> Ideally most functionalities should be covered by both unit tests and functional tests. This means, every time when you add a new functionality, you should also add unit tests, which is stored in *SRC_test.go*, as well as a [functional test](./functional/README.md), located under directory *./functional/*.
> Note that when adding a unit test under a new directory, you need to make sure that the new directory must be added to *TESTABLE* in [./test](./test). Without doing that, CI cannot run the new unit tests at all. Even build errors cannot be automatically detected.
=> CONTRIBUTING: add description about adding tests

Documentation/examples/example-deployment.md
Fixes https://github.com/coreos/fleet/issues/1607
=> Removed visible credentials

functional/scheduling_test.go
The last part of ``TestScheduleReplace`` has been occasionally failing with 2 units being active, instead of 1 active unit. Its reason is probably because the circular replace test has been running immediately after a simple replace test. Even if one of the units was destroyed before testing circular replace, the other unit remained scheduled on the other
machine, which prevented a new unit from detecting the existing unit as circular replaces. That resulted in a pretty subtle undefined state.
To fix this issue, split the last part of ``TestScheduleReplace`` into a new test ``TestScheduleCircularReplace``, so that the circular replace part could start in a fresh status. This will improve code readability too.
=> functional: split part of TestScheduleReplace into ScheduleCircularReplace

fleetctl/fleetctl.go
Use time ticker in `waitForSystemdActiveState()` just like other parts of fleet, instead of going into a loop with an arbitrary max number.
=> fleetctl: use time ticker in waitForSystemdActiveState

fleetctl/fleetctl.go
`getClient()` has not taken into account the case of `!experimentalAPI`, before calling registryClient. It has set endPoint to a specific value of URLs, but the new value would not be passed to `getRegistryClient()`, which simply fetches endPoint again. This was a regression since 848d3561 ("fleetctl: convert cli to cobra").
To fix that, introduce `getEndpoint()` that does GetString("endpoint") as well as the special handling for experimentalAPI. And make `getRegistryClient()` call `getEndpoint()`.
Fortunately, the experimentalAPI flag is set to true by default, so this special handling path is not actively used after all. Just for correctness.
=> fleetctl: take experimentalAPI into account in getClient

Documentation/api-v1.md, Documentation/deployment-and-configuration.md, Documentation/fleet-k8s-compared.md, Documentation/rkt_guide.md
These were detected by marker.
=> docs: fix broken links
